### WAVES

### ===============================
###             USERS
### ===============================

### REGISTER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif",
	"name": "Alex",
	"lastname": "Paclin",
	"role": 1
}

### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif"
}

### AUTH
GET http://localhost:3000/api/users/auth
Content-Type: application/json

### LOGOUT
GET http://localhost:3000/api/users/logout
Content-Type: application/json

### ===============================
###             BRAND
### ===============================

### ADD BRAND
POST http://localhost:3000/api/product/brand
Content-Type: application/json

{
	"name": "Ibanez"
}

### GET LIST OF BRANDS
GET http://localhost:3000/api/product/brands
Content-Type: application/json

### ===============================
###             WOODS
### ===============================

### ADD WOOD
POST http://localhost:3000/api/product/wood
Content-Type: application/json

{
	"name": "alder"
}

### GET WOODS
GET http://localhost:3000/api/product/woods
Content-Type: application/json