### REGISTER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif",
	"name": "Alex",
	"lastname": "Paclin"
}

### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif"
}

### AUTH

GET http://localhost:3000/api/users/auth
Content-Type: application/json

### LOGOUT
GET http://localhost:3000/api/users/logout
Content-Type: application/json

