### ===============================
###             WAVES
### ===============================

### ===============================
###             USERS
### ===============================

### REGISTER
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif",
	"name": "Alex",
	"lastname": "Paclin",
	"role": 1
}

### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email": "alex.paclin@gmail.com",
	"password": "ghjcnjrdfif"
}

### AUTH
GET http://localhost:3000/api/users/auth
Content-Type: application/json

### LOGOUT
GET http://localhost:3000/api/users/logout
Content-Type: application/json

### ===============================
###             BRAND
### ===============================

### ADD BRAND
POST http://localhost:3000/api/product/brand
Content-Type: application/json

{
	"name": "Ibanez"
}

### GET LIST OF BRANDS
GET http://localhost:3000/api/product/brands
Content-Type: application/json

### ===============================
###             WOODS
### ===============================

### ADD WOOD
POST http://localhost:3000/api/product/wood
Content-Type: application/json

{
	"name": "alder"
}

### GET WOODS
GET http://localhost:3000/api/product/woods
Content-Type: application/json

### ===============================
###            PRODUCTS
### ===============================

### ADD ARTICLE
POST http://localhost:3000/api/product/article
Content-Type: application/json

{
    "name": "AZ2040",
    "description": "Super awesome guitar",
    "price": 2000,
    "brand": "5b2c11d2d37177aedfd6d962",
    "shipping": true,
    "available": true,
    "wood": "5b2c1c88255983b4795f8fdb",
    "frets": 22,
    "publish": true
}

### GET ARTICLES BY ID
GET http://localhost:3000/api/product/articles_by_id?id=5b2d3648ca6a03cd33af924c,5b2d38027d75e2cdcb31cf04&type=array
Content-Type: application/json

### GET NEW ARRIVALS
GET http://localhost:3000/api/product/articles?sortBy=createdAt&order=desc&limit=4
Content-Type: application/json

### GET BEST SELLERS
GET http://localhost:3000/api/product/articles?sortBy=sold&order=desc&limit=100&skip=5
Content-Type: application/json
